default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  primary:
    <<: *default
    database: app_production

  cache:
    <<: *default
    database: app_production # まずは primary と同じにしておく（分けたいなら後で別DB）

  queue:
    <<: *default
    database: app_production # 同上