default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  username: user
  password: password
  host: db

test:
  <<: *default
  database: app_test
  username: user
  password: password
  host: db

production:
  url: <%= ENV['DATABASE_URL'] %>
  replicas: {}
  cache: {}