name: Deploy and Migrate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8 # あなたの .ruby-version に合わせる

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --without development test

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      - name: Run migrations
        env:
          RAILS_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rails db:migrate
