name: RuboCop

on:
  pull_request:
    paths:
      - 'backend/**.rb'
      - 'backend/Gemfile'
      - 'backend/.rubocop.yml'
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # ✅ これは run: に効くのでOK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.8'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: |
          cd backend
          bundle exec rubocop
